// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocalTimeController from "./local_time_controller"
application.register("local-time", LocalTimeController)

import PredictionFormController from "./prediction_form_controller"
application.register("prediction-form", PredictionFormController)

import PredictionScopeController from "./prediction_scope_controller"
application.register("prediction-scope", PredictionScopeController)

import FixtureModalController from "./fixture_modal_controller"
application.register("fixture-modal", FixtureModalController)
