service: futpred

image: victoravellog/futpred

servers:
  web:
    hosts:
      - <%= ENV['DEPLOY_HOST'] %>
  job:
    hosts:
      - <%= ENV['DEPLOY_HOST'] %>
    cmd: bundle exec sidekiq

proxy:
  ssl: true
  host: futpred.com

registry:
  server: ghcr.io
  username: victoravellog
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - FUTPRED_DATABASE_PASSWORD
  clear:
    DATABASE_HOST: futpred-db
    REDIS_URL: redis://futpred-redis:6379/0
    RAILS_LOG_LEVEL: info

volumes:
  - "futpred_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  cache:
    type: registry
    image: victoravellog/futpred-build-cache

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

accessories:
  db:
    image: postgres:17
    host: <%= ENV['DEPLOY_HOST'] %>
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: futpred
        POSTGRES_DB: futpred_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    host: <%= ENV['DEPLOY_HOST'] %>
    port: "127.0.0.1:6379:6379"
    directories:
      - data:/data
