module TeamNames
  TRANSLATIONS = {
    "Algeria" => "Argelia",
    "Argentina" => "Argentina",
    "Australia" => "Australia",
    "Austria" => "Austria",
    "Belgium" => "Bélgica",
    "Bolivia" => "Bolivia",
    "Bosnia-Herzegovina" => "Bosnia-Herzegovina",
    "Brazil" => "Brasil",
    "Cameroon" => "Camerún",
    "Canada" => "Canadá",
    "Chile" => "Chile",
    "China PR" => "China",
    "Colombia" => "Colombia",
    "Costa Rica" => "Costa Rica",
    "Croatia" => "Croacia",
    "Curaçao" => "Curazao",
    "Czech Republic" => "República Checa",
    "Denmark" => "Dinamarca",
    "Ecuador" => "Ecuador",
    "Egypt" => "Egipto",
    "England" => "Inglaterra",
    "Finland" => "Finlandia",
    "France" => "Francia",
    "Germany" => "Alemania",
    "Ghana" => "Ghana",
    "Greece" => "Grecia",
    "Honduras" => "Honduras",
    "Hungary" => "Hungría",
    "Iceland" => "Islandia",
    "Iran" => "Irán",
    "Iraq" => "Irak",
    "Ireland" => "Irlanda",
    "Israel" => "Israel",
    "Italy" => "Italia",
    "Ivory Coast" => "Costa de Marfil",
    "Jamaica" => "Jamaica",
    "Japan" => "Japón",
    "Korea Republic" => "Corea del Sur",
    "Mexico" => "México",
    "Morocco" => "Marruecos",
    "Netherlands" => "Países Bajos",
    "New Zealand" => "Nueva Zelanda",
    "Nigeria" => "Nigeria",
    "North Macedonia" => "Macedonia del Norte",
    "Norway" => "Noruega",
    "Panama" => "Panamá",
    "Paraguay" => "Paraguay",
    "Peru" => "Perú",
    "Poland" => "Polonia",
    "Portugal" => "Portugal",
    "Qatar" => "Catar",
    "Romania" => "Rumania",
    "Russia" => "Rusia",
    "Saudi Arabia" => "Arabia Saudita",
    "Scotland" => "Escocia",
    "Senegal" => "Senegal",
    "Serbia" => "Serbia",
    "Slovakia" => "Eslovaquia",
    "Slovenia" => "Eslovenia",
    "South Africa" => "Sudáfrica",
    "Spain" => "España",
    "Sweden" => "Suecia",
    "Switzerland" => "Suiza",
    "Tunisia" => "Túnez",
    "Turkey" => "Turquía",
    "USA" => "Estados Unidos",
    "Ukraine" => "Ucrania",
    "United States" => "Estados Unidos",
    "Uruguay" => "Uruguay",
    "Venezuela" => "Venezuela",
    "Wales" => "Gales",
    "Cape Verde Islands" => "Cabo Verde",
    "Congo DR" => "RD Congo",
    "Côte d'Ivoire" => "Costa de Marfil"
  }.freeze

  def self.translate(name, locale: I18n.locale)
    return name unless locale.to_s == "es"
    TRANSLATIONS[name] || name
  end
end
