name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  setup-container:
    uses: ./.github/workflows/setup-container.yml
    permissions:
      packages: write
      contents: read

  scan_ruby:
    needs: setup-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/futpred-dev:${{ needs.setup-container.outputs.container_tag }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan for common Rails security vulnerabilities
        run: bin/brakeman --no-pager

  lint:
    needs: setup-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/futpred-dev:${{ needs.setup-container.outputs.container_tag }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    needs: setup-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/futpred-dev:${{ needs.setup-container.outputs.container_tag }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/futpred_test
        run: bin/rails db:test:prepare && bundle exec rspec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
